### ISSUE TITLE
[Feature Request] Ability to adjust the length of the day/night cycle

### ISSUE THREAD

**Issue by Papzzz** [nxPublic/ValheimPlus#54]
Before i get to the request, just want to say thank you for the effort you've done on this so far, absolutely amazing work!

Anyway, i've not seen this requested yet but would it be possible to add the ability to adjust the day/night cycle to be either slower or faster?

**Comment by nxPublic** [comment]
A night time speed modifier will be provided for 0.8.5

Due to the way time is handled, I would rather not tinker around with the day time.
Because I would either be forced to reset time to a fixed value for a specific amount of time and then let it run again when the extra duration is over or I'd need to modify the actual in game time that is a not tied to the actual server time. If i would do that your world would get out of sync with the actual world time. So its a tricky thing.

However, 0.8.5 will include:
```ini
[Time]
TotalDayTimeInSeconds=1200
nightTimeSpeedMultiplier=0 ;will increase the time by % in speed
```
This will allow you to have faster passing nights and longer days in conjunction with each other.
The smartest solution i was able to come up with.
